### PR TITLE
Refactoring of the CLDF Ontology

### LINKED ISSUE #49: Slicing, indexing, subsetting: counting!
**Proposal**

Concerning `slicing` as used [here](https://github.com/cysouw/cldf/tree/master/components/partialcognates):

This is yet another "tab vs. comma" discussion, as there are at least two different approaches to counting: first the slicing from Python/C, where the counter starts at zero and the end is not included (basically you are counting boundaries here), and second the indexing/subsetting from Matlab/R, where the counter starts at one and the end is included (basically you are counting elements here).

Please note: I am perfectly aware that the two approach are equivalent, and I also know that this is very much a question of what you are used to. The crucial point is which approach will more quickly lead to misunderstanding when somebody uses the data without reading the documentation.

I think it important to realize that the CLDF is not a programming language, but a data description. So, it should be easily understandable for people outside a particular coding framework. I think that the 'element-counting' Matlab/R approach is *much* easier to grasp intuitively than the 'boundary-counting' Python/C approach.

If you have seven elements (with six explicit boundaries coded in the data), and you want to refer to the third element, then using "3" seems more natural than using "2:3". The same if you want to refer to elements 1 through 4, then "1:4" seems more natural than "0:4" (the more so as the boundary at "0" does not exist in the data).

So: my proposal is to not use "slicing" but "element counting" in the CLDF.

### LINKED ISSUE #52: segmentsSlice should be a property in the Ontology
rather than the under-specified `slice` property.

See also #49

### LINKED ISSUE #56: Capitalise glottocode csvw column name
To keep the schema more consistent, the default column name for the `glottocode` property should be `Glottocode`.

Addresses #54

### LINKED ISSUE #57: Drop rdfs:label property in Ontology
Since we already have two more name-like attributes for each property, `csvw:name` and the local name in the CLDF namespace, an additional `rdfs:label` seems superfluous, considering that the other names are fairly human readable as well.

Addresses #54

### LINKED ISSUE #59: Drop subSequence property
The `subSequence` property isn't used anywhere and should be obsolete and replaced by specific slice properties refereing to a `sequence` property.

Addresses #54

### LINKED ISSUE #60: Specify the refered table for reference properties
Currently, a weird hack involving the `csvw:name` of reference properties is used to determine the component which is referenced. This should be replaced by explicitly specifying the referenced component in the Ontology. With this in place, we should also regularize the `csv:name` of reference properties (see #54 ).

### LINKED ISSUE #61: Merge cognates and partialcognates components

### LINKED ISSUE #62: Small naming issues in ontology
Proposal to rename default `csvw:name` of the following properties, because there is no reason for them to be different:

* url `#primaryText`: rename csvw:name to `Primary_Text`
* url `#analyzedWord`: rename csvw:name to `Analyzed_Word`
* url `#translatedText`: rename csvw:name to `Analyzed_Text`
* url `#motivationStructure`: rename csvw:name to `Motivation_Structure`
* url `#prosodicStructure`: rename csvw:name to `Prosodic_Structure`
* url `#metaLanguageReference` : rename csvw:name to  `Meta_Language_ID`
* url `#sourceFormReference`: rename csvw:name to `Source_Form_ID`
* url `#targetFormReference` ->: rename csvw:name to `Target_Form_ID`

(extracted from #54)

### LINKED ISSUE #63: Problematic naming issues in ontology
These issues might be more involved, but if we do not change it now, then it will probably never be possible again!

- url `#iso639P3Code` is apparently named this way following lexvo.org. The csvw:name is `Iso`, which I find strange. I would propose csvw:name `ISO_639_Part_3_Code` or `ISO639P3code`
- url `#lexicalUnit`, but csvw:name `Form`. I think the name of the propertyURL is too restrictive as we do not only use this for lexical units. Consider changing the propertyURL to `#form`
- url `#soundSequence`, but csvw:name `Segments`. I would urge to decide for one or the other. There is no reason to confuse people even more ;-).
- the combination propertyURL `#conceptSet` and csvw:name `Concepticon_ID` is confusing. Can we come up with something better here?

(extracted from #54)

### PR DESCRIPTION
**Pull request by xrotwang**
mostly fixing naming issues, in particular
- closes #63
- closes #62
- closes #57
- closes #56

but also
- closes #61
- closes #60
- closes #59
- closes #49
- closes #52

### CODE REVIEW

**Comment by LinguList** [comment]
Do we have an example for how partial cognates would now be rendered? Did we decide on the secondary segmentation?

**Comment by LinguList** [comment]
I was thinking: given that we have an almost functioning export to cldf in lingpy, we might try to keep publication of cldf-1.0 in sync with testing whether the export to and from works in lingpy? As there we get sources for partial cognates and other things, it may be useful for testing pycldf, right?

**Comment by xrotwang** [comment]
I think  we have to go step by step. Now CLDF tomorrow pycldf. Doing all
in one go  is pretty big.

Am 27.11.2017 5:24 nachm. schrieb "Johann-Mattis List" <
notifications@github.com>:

**Comment by xrotwang** [comment]
Also, all I did was adding the segmentsSlice column to the cognates table.
So nothing changed on cell encoding level.

Am 27.11.2017 6:03 nachm. schrieb "Robert Forkel" <xrotwang@googlemail.com>:

**Comment by LinguList** [comment]
I see. For me, this is all good to go and can be merged.

**Comment by xrotwang** [comment]
I'm merging this now, mainly to keep moving. Individual changes may be rolled back later upon request :)

**Pull request merged**
