### PR TITLE
V1.2

### PR DESCRIPTION
**Pull request by xrotwang**

### CODE REVIEW

**Comment by xrotwang** [comment]
@fmatter what do you think about the additions to CLDF Markdown proposed at
https://github.com/cldf/cldf/blob/cb0bdc93c535826adfe7965160df65c4318aa8ab/extensions/markdown.md#dataset-mappings-in-yaml-frontmatter

**Comment by fmatter** [comment]
With a setup like

```
---
cldf-datasets: {
  wals: https://doi.org/10.5281/zenodo.6806407#rdf:ID=wals
  apics: https://doi.org/10.5281/zenodo.3823888#rdf:ID=apics
}
---
```

would a text document use e.g. `[](ExampleTable#cldf:apics:3-32)` and `[](ExampleTable#cldf:wals:igt-8)`? Or how would prefixes work?

Also, is the idea that you could run `cldfbench cldfviz.text` on a document containing the frontmatter above, and then cldfviz would resolve it as described [here](https://github.com/cldf/cldf/blob/cb0bdc93c535826adfe7965160df65c4318aa8ab/extensions/discovery.md#Example)?

**Comment by fmatter** [comment]
### CLDF Markdown in CLDF datasets

Does valid CLDF markdown include HTML elements? I.e., can I use `"dc:conformsTo": "CLDF Markdown"`?

(`pylingdocs` uses pure HTML for different things:

* crossreferences to tables, figures, sections (`<a href='#tab:verbprefixes' class='crossref' name='tab:verbprefixes'>ref</a>`)
* captions (`<div class='caption table' id='tab:verbprefixes'>Person marking prefixes on verbs</div>`)
* smallcaps (`<span class='smallcaps'>3p</span>`)

These elements are then correctly rendered by `clld-document-plugin`, using [javascript](https://github.com/fmatter/clld-document-plugin/blob/main/src/clld_document_plugin/static/clld-document.js#L54-L140) and [CSS](https://github.com/fmatter/clld-document-plugin/blob/main/src/clld_document_plugin/static/clld-document.css).)

**Comment by fmatter** [comment]
Suggestions for the spec document:

* add example to **Passing additional info to processors**, like `[Example 1](ExampleTable?with_primaryText#cldf:ex1)` for including the `Primary_Text` line.
* include example in **Referencing data from multiple datasets**
* insert cross reference from **Dataset mappings in YAML frontmatter** to **Referencing data from multiple datasets**

**Comment by fmatter** [comment]
Looks overall good to me, though!

**Comment by xrotwang** [comment]
> Also, is the idea that you could run `cldfbench cldfviz.text` on a document containing the frontmatter above, and then cldfviz would resolve it as described [here](https://github.com/cldf/cldf/blob/cb0bdc93c535826adfe7965160df65c4318aa8ab/extensions/discovery.md#Example)?

Yes, that's the idea. I should add - as implementation note - that CLDF Markdown processors may provide ways to override mappings via frontmatter. E.g. in cases where you already have local copies of the relevant data, you would be able to run `cldfbench cldfviz.text --dataset-mappings '{"wals": "../wals","apics": "../apics"}'` or similar.

**Comment by xrotwang** [comment]
> Does valid CLDF markdown include HTML elements? I.e., can I use `"dc:conformsTo": "CLDF Markdown"`?

Yes, I think so. CLDF Markdown is "just markdown - but with potentially broken links" :) The only complication I see with including arbitrary HTML in CLDF Markdown is that it may break markdown link detection - but at least `[]` and `()` are not used in the HTML syntax.

**Comment by xrotwang** [comment]
@SimonGreenhill could you review https://github.com/cldf/cldf/blob/2a8f4c64fd49469f4e1905df8b5cf33f962d1363/components/trees/README.md ?

**Comment by SimonGreenhill** [comment]
@xrotwang  -- looks good to me, thanks!

**Pull request merged**
